TryGhost/node-sqlite3

package.json
src/database.cc
src/statement.cc

refs #385 and https://github.com/iojs/io.js/issues/456

Upgrade to nan@1.5.0 / Fix compile against io.js

---

binding.gyp
deps/sqlite3.gyp
package.json

Fix glibc missing symbol errors

---

README.md

add common instructions for linux as well as link to sqlcipher build instructions

correct instructions for building against sqlcipher

---

CONTRIBUTING.md

- Users are prompted to view this guide before raising an issue. 
- Putting it here as well as in the wiki may help more people to see the info needed to debug their install.

Add install help guide to contributing.md

---

package.json

https://github.com/mapbox/node-pre-gyp/pull/170

Upgrade node-pre-gyp to support custom binary hosting mirror

---

.travis.yml
appveyor.yml
package.json
scripts/build-appveyor.bat

Add support for node v8 to travis+appveyor

---

.travis.yml
appveyor.yml
cloudformation/ci.template.js
package.json

This updates the CI user configuration to use a CFN template and remove the encrypted variables from travis/appveyor.
cc @mapbox/core-tech

update ci user

---

.travis.yml
appveyor.yml
package.json

Node v10 support (WIP)

---

.travis.yml
appveyor.yml
scripts/build-appveyor.bat
scripts/build_against_electron.sh
scripts/build_against_node.sh
test/each.test.js
test/support/createdb-electron.js
test/support/createdb.js

See #811 for initial PR.
- Fixed GYP_ARGS issue
https://github.com/mapbox/node-sqlite3/pull/976/files#diff-d3bcfe1f6e2dbb503917dadba6a302fcR13
- Fixed merge conflicts

add electron builds to ci (continued)

---

package.json

Fixes https://github.com/mapbox/node-sqlite3/issues/1035

Update node-pre-gyp to 0.11

---

package.json

Result expected in build/stage/
Relate-to: https://github.com/mapbox/node-sqlite3/pull/1028
Change-Id: If0fd4574924149a59d510914cb872eab259bc6d5
Signed-off-by: Philippe Coval <p.coval@samsung.com>

build: Add npm run pack to build binary package

---

README.md
deps/sqlite3.gyp

Alternative fix for #1084.
Just if of interest :-)

Allow specifying the python to use.

---

test/issue-108.test.js

Fix incorrect test (#108)

---

.travis.yml
appveyor.yml
scripts/build-appveyor.bat
scripts/install_node.sh

Just trying it out, sorry for the noise.

Node 12 workaround in Appveyor

---

CHANGELOG.md
Makefile
README.md
package.json
scripts/build_against_node.sh
scripts/build_against_node_webkit.sh
scripts/build_for_node_webkit.cmd

Fixes a few usages of http that should be https

Use https: instead of http:

---

.travis.yml
appveyor.yml

Add electron 8

---

deps/sqlite3.gyp

enable 'SQLITE_ENABLE_DBSTAT_VTAB=1'

---

package.json

fix: [BUG] yarn 2 pnp issues #1312

---

.travis.yml
appveyor.yml

https://www.electronjs.org/releases/stable?version=7

prebuilt: add electron 7.2

---

Dockerfile

Change-Id: I79000463955d16eec8809c870f7d02c60da53432
Bug: https://github.com/mapbox/node-sqlite3/issues/418
Relate-to: https://github.com/mapbox/node-sqlite3/pull/1028
Origin: https://github.com/tizenteam/node-sqlite3
Signed-off-by: Philippe Coval <rzr@users.sf.net>

build: Install files to be deployed

---

deps/sqlite3.gyp

Fixes https://github.com/mapbox/node-sqlite3/pull/1447

sqlite3: enable math functions

---

.github/workflows/ci.yml

- renamed variables in prep for host != target builds
- added more debug info to step after building binary
- altered job name to include more system info
- configured builds to always be verbose

Improved CI workflow

---

src/async.h
src/threading.h

refs https://github.com/TryGhost/node-sqlite3/issues/137#issue-14093402
- we don't actually need to depend on Boost for mutexes

Switched to libuv mutexes
