src/gcc-preinclude.h
The inclusion of gcc-preinclude.h breaks the build on ARM because of
the missing .symver symbol.  Only define it on x86.
Closes out mapbox/node-sqlite3#445.
=> Fix non-x86 build failure.

src/gcc-preinclude.h
gcc-preinclude.h contains a fix for old Linux systems but it's included
unconditionally on other platforms as well.
I could update the GYP files to exclude it on other platforms but it
seems easier to add a `defined(__linux__)` guard to the header file.
Let this be the last fix.
Refs #445.  R=@springmeyer?
=> Fix non-Linux build failure.

deps/sqlite3.gyp, test/json.test.js
ref #532
Enables the [JSON1 extension](https://www.sqlite.org/json1.html) added in 3.9.0, and adds a test to confirm the `json()` function exists.
=> Enable json1 extension by default

scripts/build-appveyor.bat
Seems to work (AppVeyor's [build](https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.426) is green).
Fixes appveyor/ci#497 (not really, but works around it).
Fixes #549.
Fixes #557.
Might need `git commit --allow-empty -m "[publish binary]"` in a separate branch (or not really empty, but containing only the necessary AppVeyor config, something very similar to 9cdebff97712bf810f1cf96bc700887090db20fc).
=> explicitly set platforms for `powershell Install-Product` on AppVeyor

src/database.cc, src/database.h, test/interrupt.test.js
This change adds support for [sqlite3_interrupt](https://www.sqlite.org/c3ref/interrupt.html). This makes it possible to interrupt a long running query.
I called the function synchronously instead of going through `db->Schedule` because if it was scheduled it wouldn't be possible to interrupt `exec`. This is because while `exec` is running the work queue is not processed. Also, the `sqlite3_interrupt` function doesn't do any I/O or acquire any locks, so it won't block the javascript thread.
The downside of calling `sqlite3_interrupt` synchronously means that it has to check whether the database is open, and has to check that `sqlite3_close` is not about to be run by another thread. Basically, if `sqlite3_interrupt` is called on an already closed database, then it could cause memory …
=> Add support for sqlite3_interrupt

src/database.cc, src/database.h, test/interrupt.test.js
This reintroduces #518, fixing the test failure that caused it to be reverted in #630. The test failure was happening because the interrupt test used common table expressions, and common table expressions are not supported on older versions of sqlite. I removed the use of common table expressions in the interrupt test to fix it.
=> Add support for sqlite3_interrupt (with fixed test)

test/interrupt.test.js
@springmeyer I'm sorry to have broken the build twice and caused so much trouble. The reason that the test failed this time is that `db.exec` does not not block other queries from starting in `db.serialize` mode. This is mentioned in issue #41.
I was using `db.exec` to create a test table `t`. Depending on the order that the worker threads did stuff, that might not have happened before the query that used the table `t` was run. I fixed this by waiting for `db.exec` to complete before continuing with the rest of the test.
Sorry again.
=> Fix interrupt test: wait for exec to complete before continuing with test

src/async.h
`uv_ref()` can't be called from the non-event-loop thread. Furthermore,
it is not necessary in `async.h`, because open `uv_async_t` is already
holding the event loop from exiting.
See: #702
cc @jlongster
_(NOTE: Tests for current master fail on my machine, so please check it with care!)_
=> async: remove racey `uv_ref()`/`uv_unref()`

package.json
The 0.6.32 version of node-pre-gyp supports npm configuration for CA bundles.
=> Upgrade node-pre-gyp to version 0.6.32

README.md
(PR requested per issue #872)
I've added a section to the readme addressing extra steps needed to get sqlite3+sqlcipher running in an Electron app.
I've only got about two days of actual experience working with Electron and Node.js applications, so it may be worth taking a close look at what I've written to address any inaccuracies.
=> Added note about custom builds & Electron

.travis.yml, binding.gyp, deps/sqlite3.gyp
We've long had a trick in the build system to apply:
```c
__asm__(".symver memcpy,memcpy@GLIBC_2.2.5");
```
to the code dynamically when compiling the binaries on linux.
Without this trick the binaries will end up having a runtime link to `memcpy@@GLIBC_2.14` within `libc` due to [how symbol versioning works for libc](https://github.com/springmeyer/glibcxx-symbol-versioning).
With this trick the binaries will only depend on `memcpy@GLIBC_2.2.5`, which allows them to work without upgrading libc on older linux systems.
The problem with this approach was that it could break on different linux versions that don't use glic. So this PR moves the logic such that it is only applied on travis builds for binaries. This means that source compiles will not use the hack and anyone needing to build for …
=> Fix logic to allow binaries to run on old centos

appveyor.yml, package.json, scripts/build-appveyor.bat
Starts:
- Building with `msvs_toolset=14` when using > node v4
- Fixes node v9 build which requires `msvs_toolset=14` and `Visual Studio >= 2015` to support `constexpr` - refs #920
=> Visual studio build fixes

.travis.yml, CHANGELOG.md, README.md, appveyor.yml, package.json
=> Upgrade node-pre-gyp to version 0.9.0

package.json, scripts/mocha-as-worker.js, src/async.h, src/database.cc, src/database.h, src/macros.h, src/statement.cc, src/statement.h
Properly tracks which event loop callbacks should be dispatched on so that node doesn't busy loop on the main thread if node-sqlite3 is called from a worker.
=> Add support for running inside a node 10.5 worker_thread

.travis.yml, scripts/build_against_node.sh
This removes coverage, which was breaking the builds. It's a short-term solution so others don't get unnecessarily stuck. Long-term solution is described in #1061 
cc @springmeyer @kewde
=> remove coverage

package.json
Updating node-pre-gyp to 0.11 fixes a compile error caused by nodejs/node#21063 and mapbox/node-pre-gyp#391. The issue irregularly occurs due to upstream changes to callbacks which, following a download failure, can cause duplicate callbacks which result in two builds of sqlite3 instead of one; the build consequently fails because the second build often removes files created by the first build. See: mapbox/node-pre-gyp#408
=> Fix compile issue introduced by nodejs change (increment node-pre-gyp version)

package.json, src/database.cc, src/macros.h, src/statement.cc
* Remove use of two argument `Concat`
Refs: https://github.com/nodejs/node/issues/25060
=> make compatible with V8 7.1

binding.gyp, lib/sqlite3.js, src/backup.cc, src/backup.h, src/database.h, src/macros.h, src/node_sqlite3.cc, test/backup.test.js
This exposes the sqlite3 backup api as described at https://sqlite.org/backup.html.
This implementation draws on https://github.com/mapbox/node-sqlite3/pull/883, extending it to create a backup object that can be used in the background, without leaving the database locked for an extended period of time.  This is crucial for making backups of large live databases in a non-disruptive manner. Example usage:
```js
var db = new sqlite3.Database('live.db');
var backup = db.backup('backup.db');
...
// in event loop, move backup forward when we have time.
if (backup.idle) { backup.step(NPAGES); }
if (backup.completed) { /* success! backup made */  }
if (backup.failed)    { /* sadness! backup broke */ }
// do other work in event loop - fine to modify live.db
...
```
Here is how sqlite's backup api …
=> add backup api that can be run incrementally

scripts/build-appveyor.bat, scripts/build_against_electron.sh
electron-mocha dropped support for node 6 in their 8.0.0 release - https://github.com/jprichardson/electron-mocha/blob/master/CHANGELOG.md
(Just triggering the CI for now, apologies for any noise.)
=> Test fix - specify electron-mocha version.

tools/docker/architecture/linux-arm64/Dockerfile, tools/docker/architecture/linux-arm64/run.sh
Bug: https://github.com/mapbox/node-sqlite3/issues/903
Change-Id: Ic91292879deed92fcffd90d7b2d79f551c5b06f4
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> tools: Crossbuild for ARMv8-64

.travis.yml
Alternative to #1165 as Trusty seems to be the lowest release supported by the official Node build.
=> ci: remove accidental distro upgrade

.travis.yml, appveyor.yml
These version were missed as reported by #1163
=> prebuilt: add electon 4.1 & 4.2

tools/docker/architecture/linux-arm/Dockerfile, tools/docker/architecture/linux-arm/run.sh
Raspbian is used as base
It took less than 20 min to build on Ubuntu 18.04 x86_64
If merged other arch will come next, and then automated by CI.
Relate-to: https://github.com/mapbox/node-sqlite3/issues/418
Change-Id: Ic92baf3e019e28862a24d84728835a641a6838c1
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> tools: Crossbuild for ARMv7

.travis.yml, appveyor.yml
This adds support for Electron 6.0.0. I used the same technique as https://github.com/mapbox/node-sqlite3/pull/1160 and https://github.com/mapbox/node-sqlite3/pull/1180.
Electron 6.0.0 was released on 7/30/2019.
https://electronjs.org/releases/stable#release-notes-for-v600
=> prebuilt: add electron 6.0.0

deps/common-sqlite.gypi
node-gyp uses 'msbuild_toolset' in 'target_defaults' to specify what toolset should be used, according to what version of Visual Studio was detected.
Before this change, when 'toolset' was not specified, node-sqlite3 failed to compile with any version of Visual Studio after 2015, because gyp fails to detect the toolset correctly.
With this change 'toolset' is only used if defined, fixing compilation with node-gyp and recent VS versions.
=> overwrite 'msbuild_toolset' only if 'toolset' is defined

.travis.yml
Not sure if this change is right, but wondering if this is the reason the CI was failing with Electron 7.
Looks like the minimum supported node version for Electron 7 is Node 8
=> Use minimum supported node version for Electron 7

README.md, appveyor.yml, scripts/build_against_electron.sh
Deprecated since Electron v7.0.
https://github.com/electron/electron/blob/master/docs/breaking-changes.md#node-headers-url
=> Fix Electron dist url

scripts/build-appveyor.bat
Use #1245 for Electron v1 - v4.
cf. https://github.com/nodejs/node-gyp/pull/1934
result
https://ci.appveyor.com/project/mtgto/node-sqlite3/builds/30962351
=> deps: alternative update of node-gyp for electron (v1 - v4), windows

README.md
This PR adds a single mention to the bundled extension in the README.md file, to help surface this important feature inclusion, in hopes of saving others the time and anguish it took me to figure it out.
Per [PR 538](https://github.com/mapbox/node-sqlite3/pull/538/files), support for the [json1](https://www.sqlite.org/json1.html) extension has been bundled in the npm distribution since late 2015. However, this feature isn't surfaced anywhere in the documentation, or the wiki, and the only way to discover it is via reading the build configs or searching the closed PRs. Since json1 is the first extension listed in the [official docs](https://www.sqlite.org/docs.html), it makes sense to mention this inclusion in the docs.
Alternatively, a "bundled extensions" wiki entry could be created to …
=> Added json1 support note

lib/trace.js, test/verbose.test.js
Fixes #1316 
Currently, `verbose()` adds trace info to the error object **only** if you `throw` the error by catching it inside a try/catch :
https://github.com/mapbox/node-sqlite3/blob/afa22076ba13ef3bc6afac892d9ed46a7ec36fc2/lib/trace.js#L18-L28
This doesn't work with promises as discussed in the linked issue because throwing in an async callback doesn't get caught by the promise or a wrapping try/catch.
this PR solves this issue by simply adding the trace info outside try/catch by checking the error object which is always the first argument.
=> Don't require throw to add trace info for verbose mode

package.json, src/statement.cc
(While investigation of #1335) I found some bad c-string comparison.
C++ compiler already warns this bug in CI.
example https://travis-ci.org/github/mapbox/node-sqlite3/jobs/685282346#L683
IMO, this bug doesn't really seem to cause negative consequences, thanks to awesome modern C++ compiler optimization.
=> Fix bad comparison of c string

.gitignore, .travis.yml, appveyor.yml, package.json, scripts/build-appveyor.bat, src/backup.cc, src/backup.h, src/database.cc, src/database.h, src/statement.cc, src/statement.h
=> Fix worker threads crash

src/backup.cc, src/backup.h, src/database.cc, src/database.h, src/macros.h, src/statement.cc, src/statement.h
This PR makes `TRY_CATCH_CALL` return on failure, and to enable proper cleanup, replaces usage of `delete` with smart pointers. It also fixes two sources of segmentation faults.
Fixes #1026, fixes #1323.
=> Fix segfaults

scripts/build-appveyor.bat, scripts/build_against_electron.sh, scripts/build_against_node.sh
Executing "npm install --build-from-source" only builds the module for one of the N-API target versions. The build command has to be executed explicitly to generate builds targeting each of the specified N-API versions.
This should fix publishing binaries (which means this should fix #1424).
=> Rebuild binaries before publishing

lib/sqlite3-binding.js, package.json
This is basically the same as #1361 and also updates `node-pre-gyp`. Without updating these two I'm running into all kinds of issues trying to rebuild from source for Electron and for Apple's `arm64`.
=> Update node-gyp and node-pre-gyp

src/statement.cc, test/other_objects.test.js
Verify ToString() returns valid data before casting to utf-8 encoding.
fixes #1440 
fixes #1449
=> bug: fix segfault of invalid toString() object

package.json
refs https://github.com/TryGhost/node-sqlite3/issues/1493
refs https://github.com/nodejs/node-gyp/pull/2474
- `node-gyp` 7.x has a minimum `tar` version of 6.0.2, which has a
security vulnerability listed against it
- `node-gyp` 8.x updates the minimum to 6.1.2, which contains the fix
- `node-gyp` 8.x should still allow us to use Node 10, so we're good
with Node compatibility
- it also seems to fix the `PYTHON` env variable being set, which helps
fix the build for MacOS Monterey (coming in the next commit)
=> Updated `node-gyp` to v8.x

deps/sqlite3.gyp
refs https://github.com/nodejs/node-gyp/blob/f5fa6b86fd2847ca8c1996102f43d44f98780c4a/lib/find-python.js
refs https://github.com/TryGhost/node-sqlite3/issues/1552
- Monterey 12.3 removed Python 2, so `node-sqlite3` doesn't build because
the v3 binary is called `python3` and therefore `python` is missing
- `node-gyp` has logic to find the python binary and stores it in the `PYTHON`
env variable
- we should be able to switch to using that
=> Fixed building on MacOS Monterey 12.3

.github/workflows/ci.yml
- we weren't passing the build architecture in so it would default to
`x86`
=> Fixed Windows build architecture in CI

deps/extract.js, deps/extract.py, deps/sqlite3.gyp, package.json
node-gyp already depends on tar, so nothing new here.
This should at least reduce some problems related to Python.
=> Replaced Python extraction script with JS

.github/workflows/ci.yml
- Node 18.0.0 has been released so we should be able to start running CI
on it
=> Added Node 18 to CI

.github/workflows/ci.yml
- as we move towards cross-compiling in native GitHub Actions, we need a
way to differentiate between the host and target architecture
- this adds a concept of `host` to CI and passes the target architecture
to `node-pre-gyp`
=> Added `host` architecture concept to CI

src/statement.cc, src/statement.h
Backport of a change we did in our VSCode fork.
Authored by @deepak1556 and @sbatten
=> Address some CodeQL warnings

.github/workflows/ci.yml, tools/BinaryBuilder.Dockerfile
fixes https://github.com/TryGhost/node-sqlite3/issues/1625
- Alpine 3.16 was released in May 2022 and 5.0.9 was the first release
since it became the default for `node16-alpine`
- compiling on Alpine 3.16 broke compatiblity for Alpine 3.15
- given we should be able to just build with 3.15 and the binaries end
up forward-compatible, this commit reverts back to that
=> Restored compatibility for Alpine 3.15

.gitignore
Running `npm i` in the respository creates a `package-lock.json` file. As this file is not committed, it would be nice to have it in `.gitignore` to avoid the dirty repo state.﻿
=> Added `package-lock.json` to `.gitignore`

lib/sqlite3.js
sqlite3#verbose now returns sqlite3 instead of globalThis object when
bound to undefined (void 0). This enables importing verbose in
typescript using `import { verbose as sqlite3 } from "sqlite3"`. Because
typescript automatically converts import statement to
`sqlite3_1.default.verbose();`.
=> Fixed importing `sqlite3#verbose` using destructuring syntax

lib/sqlite3.js, src/database.cc, test/update_hook.test.js
Currently there are event `insert/update/delete` events defined on javascript side, but they are not working c++ side.
The code was already implemented in pull request https://github.com/mapbox/node-sqlite3/pull/1174, but tests weren't added, so i decided to add them myself.
```
Error: update is not a valid configuration option
at Database.addListener.Database.on (D:\dvp\study_stack\cloudfs\node_modules\sqlite3\lib\sqlite3.js:154:14)
at SQLITE.on (D:\dvp\study_stack\cloudfs\libs\sql.js:74:15)
at test.run (D:\dvp\study_stack\cloudfs\test.js:12:14)
at <anonymous> Error: update is not a valid configuration option
at Database.addListener.Database.on (D:\dvp\study_stack\cloudfs\node_modules\sqlite3\lib\sqlite3.js:154:14)
at SQLITE.on (D:\dvp\study_stack\cloudfs\libs\sql.js:74:15)
at test.run …
```
=> Added ability to receive updates from `sqlite3_update_hook`

.github/workflows/ci.yml
Please see [this comment](https://github.com/TryGhost/node-sqlite3/pull/1594#issuecomment-1241245668):
> Hey all! 👋🏻 Whilst I would love to merge this, the generated binaries it produces get caught up with MacOS' quarantine flag, so the it requires you to remove the flag in order for it to be run, which is clearly not going to work from an end-user perspective.
>
> I can't tell if it's something I'm doing locally or whether there is some security issue I've missed.
>
> Any ideas welcome 🙂
=> Added Darwin ARM64 binaries

.github/workflows/ci.yml
fixes https://github.com/TryGhost/node-sqlite3/issues/1663
- Ubuntu 22.04 ships with a newer glibc so the prebuilt binaries end up being linked to a more recent version, removing compatibility with systems that ship with older variants
- this commit fixes that by downgrading the Ubuntu version
=> Fixed glib compatibility by downgrading to Ubuntu 20

binding.gyp
It seems that an old refactoring (~8 years) made a mistake on the way conditions are expressed in gyp. the "conditions" key cannot be set 2 times and the conditions should be all set in the "conditions" array.
The impact of this bug is that when sqlite3 is compiled against a custom sqlite3 source tree, the sqlite3 runtime keeps linking with the system sqlite3 instead of linking to the custom compiled sqlite3 library. In my case that lead to a SIGSEGV upon loading an extension.
=> Fix rpath linker option when using a custom sqlite

lib/sqlite3.d.ts
Small change, but some developers enjoy working with generics over the `any` type when using TypeScript.
Added Generics type annotations for the following methods:
- `Statement.get`
- `Statement.all`
- `Statement.each`
- `Database.get`
- `Database.all`
- `Database.each`
This will not break existing TypeScript code. It will still be possible to directly add type annotations to the row/rows.
Take into consideration the following TypeScript code:
```typescript
import sqlite3 from "sqlite3";
interface IUser {
id: string;
name: string;
email: string;
}
const db = new sqlite3.Database("./test.db");
const createTableQuery = `CREATE TABLE IF NOT EXISTS users (
id TEXT PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
email TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at …
```
=> Add generic type annotations for Statement and Database get/all/each methods callback rows

src/async.h, src/backup.cc, src/backup.h, src/database.cc, src/database.h, src/macros.h, src/statement.cc, src/statement.h, test/support/createdb.js
- Implemented RAII to ensure resource safety and exception safety
- Leveraged range-based for loops for cleaner and more efficient iteration
- Addressed and resolved all project-related warnings for enhanced code quality
=> Use of RAII and automatic type deduction.

.github/workflows/ci.yml
- Python 3.12 no longer ships with this and GHA CI has updated to 3.12, which breaks our build scripts
- this should fix that until we can update node-gyp
=> Installed setuptools in CI workflow

.github/workflows/ci.yml, .gitignore, README.md, binding.gyp, lib/sqlite3-binding.js, package.json, tools/BinaryBuilder.Dockerfile
=> Switched to prebuild + prebuild-install

src/backup.cc, src/database.cc, src/macros.h, src/statement.cc
- this fixes building in debug mode because the compiler (at least, on macOS) doesn't like the `assert(status == 0)`
- this also DRYs up some common code by moving it into a macro
=> Extracted common Node-API queuing code into macro
